name: Pull Request Flow

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "licenses/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      redis-latest: ${{ steps.redis-latest.outputs.tag }}
    steps:
      - id: redis-latest
        run: echo "tag=$(curl -s https://api.github.com/repos/redis/redis/releases/latest |
                         jq -r '.tag_name' )" >> $GITHUB_OUTPUT

  basic-test:
    needs: setup
    uses: ./.github/workflows/task-test.yml
    with:
      env: ubuntu-latest
      test-config: QUICK=1
      get-redis: ${{ needs.setup.outputs.redis-latest }}
    secrets: inherit

  coverage:
    uses: ./.github/workflows/flow-coverage.yml
    secrets: inherit

  sanitize:
    uses: ./.github/workflows/flow-sanitizer.yml
    secrets: inherit
    with:
      flow-config: QUICK=1

  pr-validation:
    needs: [basic-test, coverage, sanitize]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure')
        run: exit 1
